// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UniversitiesManagement.Infrastructure.Contracts.DbEntities
{
    public partial class UniversitiesDbTableRow
    {
        public UniversitiesDbTableRow()
        {
            WebDomains = new HashSet<WebDomainDbTableRow>();
            WebPages = new HashSet<WebPageDbTableRow>();
        }

        [Key]
        public int Id { get; set; }
        public int IdFromWebApi { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        [Required]
        [StringLength(2)]
        public string AlphaTwoCode { get; set; }
        [StringLength(50)]
        public string StateProvince { get; set; }
        [Required]
        [StringLength(50)]
        public string Country { get; set; }

        [InverseProperty("University")]
        public virtual ICollection<WebDomainDbTableRow> WebDomains { get; set; }
        [InverseProperty("University")]
        public virtual ICollection<WebPageDbTableRow> WebPages { get; set; }
    }
}