// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UniversitiesManagement.Infrastructure.Contracts.DbEntities
{
    public partial class WebPageDbTableRow
    {
        [Key]
        public int Id { get; set; }
        public int UniversityId { get; set; }
        [Required]
        [StringLength(100)]
        public string WebPageName { get; set; }

        [ForeignKey("UniversityId")]
        [InverseProperty("WebPages")]
        public virtual UniversitiesDbTableRow University { get; set; }
    }
}