// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using UniversitiesManagement.Infrastructure.Contracts.DbEntities;

namespace UniversitiesManagement.Infrastructure.Impl.ExternalConnections
{
    public partial class UniversitiesManagementContext : DbContext
    {
        public UniversitiesManagementContext()
        {
        }

        public UniversitiesManagementContext(DbContextOptions<UniversitiesManagementContext> options)
            : base(options)
        {
        }

        public virtual DbSet<UniversitiesDbTableRow> Universities { get; set; }
        public virtual DbSet<WebDomainDbTableRow> WebDomains { get; set; }
        public virtual DbSet<WebPageDbTableRow> WebPages { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-4F9R5IV\\SQLEXPRESS;Initial Catalog=UniversitiesManagement;Persist Security Info=True;User ID=sergio;Password=milla");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UniversitiesDbTableRow>(entity =>
            {
                entity.Property(e => e.AlphaTwoCode)
                    .IsRequired()
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.Country)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.StateProvince).HasMaxLength(50);
            });

            modelBuilder.Entity<WebDomainDbTableRow>(entity =>
            {
                entity.Property(e => e.DomainName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.University)
                    .WithMany(p => p.WebDomains)
                    .HasForeignKey(d => d.UniversityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_WebDomains_Universities");
            });

            modelBuilder.Entity<WebPageDbTableRow>(entity =>
            {
                entity.Property(e => e.WebPageName)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.University)
                    .WithMany(p => p.WebPages)
                    .HasForeignKey(d => d.UniversityId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_WebPages_Universities");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}