// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace SWApi.Infrastructure.Contracts.Entities.SWDB
{
    public partial class PlanetsTableRowEntity
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(25)]
        public string Name { get; set; }
        public int RotationPeriod { get; set; }
        public int OrbitalPeriod { get; set; }
        [Required]
        [StringLength(100)]
        public string Climate { get; set; }
        public long Population { get; set; }
        [Required]
        [StringLength(50)]
        public string Url { get; set; }
    }
}