// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PokeApiManagement.EntitiesDB
{
    public partial class Pokemon
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(25)]
        public string? Name { get; set; }
    }
}