// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PokeApiManagement.EntitiesDB
{
    public partial class PokeStatisticsByInitial
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string initial { get; set; }
        public int counter { get; set; }
    }
}