// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using SWApi.Infrastructure.Contracts.Entities.SWDB;

namespace SWApi.Infrastructure.Impl.ExternalConnections
{
    public partial class SWDBContext : DbContext
    {
        public SWDBContext()
        {
        }

        public SWDBContext(DbContextOptions<SWDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<PlanetsTableRowEntity> Planets { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-4F9R5IV\\SQLEXPRESS;Initial Catalog=SWDB;Persist Security Info=True;User ID=sergio;Password=milla");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PlanetsTableRowEntity>(entity =>
            {
                entity.Property(e => e.Climate)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(25);

                entity.Property(e => e.Url)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}