// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkersManagementAdminMode.Infrastructure.Contracts.Entities
{
    public partial class ITWorkerEntity
    {
        public ITWorkerEntity()
        {
            TasksTable = new HashSet<TaskEntity>();
            TeamsTable = new HashSet<TeamEntity>();
        }

        [Key]
        public int idWorker { get; set; }
        public int YearsOfExperience { get; set; }
        [Required]
        [StringLength(500)]
        public string TechKnowledges { get; set; }
        [Required]
        [StringLength(10)]
        public string Level { get; set; }
        public int? idTeam { get; set; }

        [ForeignKey("idTeam")]
        [InverseProperty("ITWorkersTable")]
        public virtual TeamEntity idTeamNavigation { get; set; }
        [ForeignKey("idWorker")]
        [InverseProperty("ITWorkersTable")]
        public virtual WorkerEntity idWorkerNavigation { get; set; }
        [InverseProperty("idWorkerNavigation")]
        public virtual ICollection<TaskEntity> TasksTable { get; set; }
        [InverseProperty("idManagerNavigation")]
        public virtual ICollection<TeamEntity> TeamsTable { get; set; }
    }
}