// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkersManagementAdminMode.Infrastructure.Contracts.Entities
{
    public partial class WorkerEntity
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Surname { get; set; }
        [Column(TypeName = "date")]
        public DateTime Birthdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Leavingdate { get; set; }

        [InverseProperty("idWorkerNavigation")]
        public virtual ITWorkerEntity ITWorkersTable { get; set; }
    }
}